/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function md5(input: string): string
export function sha256(input: string): string
export function sha512(input: string): string
export function base64Encode(input: string): string
export function base64Decode(input: string): string
export function randomUuidv4(): string
export function randomBytes(size?: number | undefined | null): Array<number>
